spring.application.name=quizzo

spring.datasource.url=jdbc:postgresql://localhost:5432/quizzo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true

jwt.access-secret=E1MS+R35Bs3ZIt/ZCJEw6tA1aCFae5rC5aBAFWsUzmY=
# 1h
jwt.access-ms=3600000

jwt.refresh-secret=UQNJDi0ycPYdQEbYiBhIc5d1Dd4SeXtdImdsoVRv3OA=
# 7d
jwt.refresh-ms=604800000